### ISSUE TITLE
Not working on Sketch Beta 43

### ISSUE THREAD

**Issue by xenio** [daneden/sketch-align-layers#1]
The plugin does not work on Sketch Beta v.43, when I choose the alignment nothing happen.
https://www.sketchapp.com/beta/

This is the error I get on the console:

`TypeError: doc.actionsController().actionWithID is not a function. (In 'doc.actionsController().actionWithID(alignment)', 'doc.actionsController().actionWithID' is undefined)
line: 12
sourceURL: /Users/sandro/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Align Layers.sketchplugin/Contents/Sketch/script.js
column: 52`

Any idea how to fix it?

**Comment by daneden** [comment]
This should be fixed in the latest version. Bohemian Coding changed the method to `actionForID` instead of `actionWithID`.
